apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-test1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/eraaster37/gitlab-test1.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
